image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker-compose build
  - docker-compose up -d
  - pwd
  
tests:
  script:
    - pwd
    - docker-compose exec ./manage test