image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
  - chmod +x ~/docker-compose
  - sudo mv ~/docker-compose /bin/docker-compose
  - docker-compose build
  - docker-compose up -d
  - pwd
  
tests:
  script:
    - pwd
    - docker-compose exec ./manage test