version: '3'

services:
  web:
    env_file:
      - env_vars.env
    build: .
    restart: always
    command:
      - /code/runserver.sh
    ports:
      - "80:8000"
    depends_on:
      - db
      - mongo
  
  db:
    image: docker.repos.cafebazaar.ir/mdillon/postgis
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=carpooling
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  mongo:
    image: mongo:latest

volumes:
  dbdata:

