version: '3'

services:
  web:
    env_file:
      - env_vars.env
    build: .
    restart: always
    command:
      - /code/runserver.sh
    ports:
      - "80:8000"
    depends_on:
      - db
      - mongo

  db:
    image: docker.repos.cafebazaar.ir/mdillon/postgis
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=carpooling
    volumes:
      - "db_data:/var/lib/postgresql/data"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "log_data:/data/db"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


volumes:
  db_data:
  log_data:
  esdata01:

