version: '3'

services:
  web:
    env_file:
      - env_vars.env
    build: .
    restart: always
    command: >
      bash -c "
        sleep 1 &&
        python3 /code/carpooling/manage.py migrate --settings carpooling.settings_docker &&
        python3 /code/carpooling/manage.py runserver 0.0.0.0:8000 --settings carpooling.settings_docker
        "
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: docker.repos.cafebazaar.ir/mdillon/postgis
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=carpooling
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:

