# Generated by Django 2.2.2 on 2019-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='source_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='source_lon',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
    ]
