# Generated by Django 2.2.2 on 2019-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190728_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='trip_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
