# Generated by Django 2.2.2 on 2019-07-31 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_auto_20190730_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'group')},
        ),
    ]
