# Generated by Django 2.2.2 on 2019-07-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='trip_description',
        ),
    ]
