# Generated by Django 2.2.2 on 2019-07-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('destination_lon', models.DecimalField(decimal_places=9, max_digits=12)),
                ('source_lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('source_lon', models.DecimalField(decimal_places=9, max_digits=12)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
