# Generated by Django 2.2.2 on 2019-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20190730_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
