# Generated by Django 2.2.2 on 2019-08-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_triprequestset'),
        ('trip', '0005_trip_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='requests',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='applicant',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='containing_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TripRequestSet'),
            preserve_default=False,
        ),
    ]
