# Generated by Django 2.2.2 on 2019-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='playlist_id',
            field=models.CharField(default=None, max_length=22),
            preserve_default=False,
        ),
    ]
