# Generated by Django 2.2.2 on 2019-08-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20190806_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='containing_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='account.TripRequestSet'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='trip.Trip'),
        ),
    ]
