# Generated by Django 2.2.2 on 2019-08-07 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0008_triprequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_request_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='containing_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='trip.TripRequestSet'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'accepted'), ('c', 'canceled'), ('d', 'declined')], default='p', max_length=2),
        ),
    ]
