# Generated by Django 2.2.2 on 2019-08-12 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_triprequestset_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequestset',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'accepted'), ('c', 'canceled'), ('d', 'declined')], default='p', max_length=1),
        ),
    ]
