# Generated by Django 2.2.2 on 2019-08-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_trip_playlist_id'),
        ('trip', '0011_auto_20190812_0800'),
    ]

    operations = [
    ]
