# Generated by Django 2.2.2 on 2019-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_auto_20190812_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='people_can_join_automatically',
            field=models.BooleanField(default=False),
        ),
    ]
