# Generated by Django 2.2.2 on 2019-08-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_trip_people_can_join_automatically'),
        ('trip', '0013_vote'),
    ]

    operations = [
    ]
