# Generated by Django 2.2.2 on 2019-08-17 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_auto_20190731_0803'),
        ('trip', '0013_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companionship',
            unique_together={('member', 'trip')},
        ),
        migrations.AlterUniqueTogether(
            name='tripgroups',
            unique_together={('group', 'trip')},
        ),
    ]
