# Generated by Django 2.2.2 on 2019-08-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_merge_20190818_0715'),
        ('trip', '0014_auto_20190817_1555'),
    ]

    operations = [
    ]
