# Generated by Django 2.2.2 on 2019-08-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_auto_20190817_1555'),
        ('trip', '0015_merge_20190818_1555'),
    ]

    operations = [
    ]
