# Generated by Django 2.2.2 on 2019-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_merge_20190820_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('wa', 'waiting'), ('cl', 'closed'), ('in', 'in route'), ('dn', 'done'), ('ca', 'canceled')], max_length=2),
        ),
    ]
