# Generated by Django 2.2.2 on 2019-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_auto_20190821_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='playlist_id',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
