# Generated by Django 2.2.2 on 2019-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_auto_20190824_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='playlist_id',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('ca', 'canceled'), ('wa', 'waiting'), ('cl', 'closed'), ('in', 'in route'), ('dn', 'done')], max_length=2),
        ),
    ]
