# Generated by Django 2.2.2 on 2019-09-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_auto_20190828_1209'),
        ('trip', '0019_auto_20190831_1538'),
    ]

    operations = [
    ]
