# Generated by Django 2.2.2 on 2019-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_merge_20190901_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='playlist_id',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
