# Generated by Django 2.2.2 on 2019-08-03 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=11, validators=[django.core.validators.RegexValidator(regex='^d{11}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='pictures/profile/'),
        ),
    ]
