# Generated by Django 2.2.2 on 2019-08-03 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190803_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^?/d{11}$')]),
        ),
    ]
