# Generated by Django 2.2.2 on 2019-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
