# Generated by Django 2.2.2 on 2019-08-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190804_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_mail_seen',
            field=models.BooleanField(default=False),
        ),
    ]
