# Generated by Django 2.2.2 on 2019-08-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_mail_is_mail_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='text',
            new_name='message',
        ),
    ]
