# Generated by Django 2.2.2 on 2019-08-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190803_0956'),
        ('account', '0005_auto_20190806_0935'),
    ]

    operations = [
    ]
