# Generated by Django 2.2.2 on 2019-08-06 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_triprequestset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequestset',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_request_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
