# Generated by Django 2.2.2 on 2019-08-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_report_resolved'),
        ('account', '0006_merge_20190806_1015'),
    ]

    operations = [
    ]
