# Generated by Django 2.2.2 on 2019-08-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20190807_0707'),
        ('account', '0007_merge_20190807_0821'),
    ]

    operations = [
    ]
