# Generated by Django 2.2.2 on 2019-08-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_comment'),
        ('account', '0008_delete_triprequestset'),
    ]

    operations = [
    ]
