# Generated by Django 2.2.2 on 2019-08-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190818_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('email',)},
        ),
    ]
